// Facebook OAuth flow helpers: URL builder, code exchange, token extension, page listing.
// All network calls go through the plain fetch API — no retry logic needed here
// (token exchanges are user-initiated, failures surface as UI errors immediately).

import type { FBPage, FBPaginatedResponse } from './types';

const FB_VERSION = 'v21.0';
const FB_BASE = 'https://www.facebook.com';
const GRAPH_BASE = 'https://graph.facebook.com';

function requireEnv(name: string): string {
  const val = process.env[name];
  if (!val) throw new Error(`Missing required env var: ${name}`);
  return val;
}

/**
 * Scopes required for Marketing OS page integration.
 *
 * `read_insights` removed (Meta 2024+): it is Advanced Access only and not
 * shown in Graph Explorer's standard picker. `pages_read_engagement` covers
 * page_fans / page_impressions / post-level metrics for page admins, which is
 * the only persona we support.
 */
const OAUTH_SCOPES = [
  'pages_show_list',
  'pages_read_engagement',
].join(',');

/**
 * Build the Facebook OAuth dialog URL.
 * `state` is a CSRF token generated by the connect route and verified in callback.
 */
export function buildAuthUrl(state: string): string {
  const appId = requireEnv('FB_APP_ID');
  const redirectUri = requireEnv('FB_REDIRECT_URI');

  const params = new URLSearchParams({
    client_id: appId,
    redirect_uri: redirectUri,
    scope: OAUTH_SCOPES,
    state,
    response_type: 'code',
  });

  return `${FB_BASE}/${FB_VERSION}/dialog/oauth?${params.toString()}`;
}

/** Exchange authorization code for a short-lived user access token. */
export async function exchangeCodeForUserToken(code: string): Promise<string> {
  const appId = requireEnv('FB_APP_ID');
  const appSecret = requireEnv('FB_APP_SECRET');
  const redirectUri = requireEnv('FB_REDIRECT_URI');

  const params = new URLSearchParams({
    client_id: appId,
    client_secret: appSecret,
    redirect_uri: redirectUri,
    code,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/oauth/access_token?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB token exchange failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { access_token?: string; error?: { message: string } };
  if (data.error || !data.access_token) {
    throw new Error(`FB token exchange error: ${data.error?.message ?? 'no access_token'}`);
  }

  return data.access_token;
}

/**
 * Exchange a short-lived user token (~1h) for a long-lived user token (~60 days).
 * FB documentation: https://developers.facebook.com/docs/facebook-login/guides/access-tokens/get-long-lived
 */
export async function extendUserToken(shortToken: string): Promise<string> {
  const appId = requireEnv('FB_APP_ID');
  const appSecret = requireEnv('FB_APP_SECRET');

  const params = new URLSearchParams({
    grant_type: 'fb_exchange_token',
    client_id: appId,
    client_secret: appSecret,
    fb_exchange_token: shortToken,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/oauth/access_token?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB token extension failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { access_token?: string; error?: { message: string } };
  if (data.error || !data.access_token) {
    throw new Error(`FB token extension error: ${data.error?.message ?? 'no access_token'}`);
  }

  return data.access_token;
}

/**
 * List all pages the user administers.
 * Returns page id, name, page-scoped access_token, and category.
 */
export async function listUserPages(userToken: string): Promise<FBPage[]> {
  const params = new URLSearchParams({
    fields: 'id,name,access_token,category',
    access_token: userToken,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/me/accounts?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB list pages failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as FBPaginatedResponse<FBPage> & {
    error?: { message: string };
  };

  if ('error' in data && data.error) {
    throw new Error(`FB list pages error: ${data.error.message}`);
  }

  return data.data ?? [];
}
