// Facebook OAuth flow helpers: URL builder, code exchange, token extension, page listing.
// All network calls go through the plain fetch API — no retry logic needed here
// (token exchanges are user-initiated, failures surface as UI errors immediately).
//
// CREDENTIALS LOOKUP: DB-first (app_setting) → env var fallback. Admin có
// thể paste FB_APP_ID + FB_APP_SECRET qua UI tại /settings/integrations
// thay vì set env và redeploy. Migration path:
//   - Dev: set env var trong .env.local
//   - Production: set qua UI (encrypted DB) hoặc env (cả 2 đều work, DB ưu tiên)

import type { FBPage, FBPaginatedResponse } from './types';
import { getSettingOrEnv } from '@/lib/settings/api-keys';

const FB_VERSION = 'v21.0';
const FB_BASE = 'https://www.facebook.com';
const GRAPH_BASE = 'https://graph.facebook.com';

/** Setting keys lưu trong app_setting + cũng support env var fallback */
export const FB_APP_ID_KEY = 'FB_APP_ID';
export const FB_APP_SECRET_KEY = 'FB_APP_SECRET';

/** Read FB App ID — DB-first, env-fallback. Throws nếu cả 2 đều thiếu
 *  hoặc placeholder. */
async function getFbAppId(): Promise<string> {
  const val = await getSettingOrEnv(FB_APP_ID_KEY);
  if (!val || val === 'placeholder' || val.length < 10) {
    throw new Error(
      'FB_APP_ID chưa cấu hình. Admin vào /settings/integrations để paste.'
    );
  }
  return val;
}

async function getFbAppSecret(): Promise<string> {
  const val = await getSettingOrEnv(FB_APP_SECRET_KEY);
  if (!val || val === 'placeholder' || val.length < 10) {
    throw new Error(
      'FB_APP_SECRET chưa cấu hình. Admin vào /settings/integrations để paste.'
    );
  }
  return val;
}

/** Check 2 cái FB credentials đã set OK chưa (không throw) — UI dùng để
 *  toggle button "Cấp quyền" enabled/disabled. */
export async function isFbAppConfigured(): Promise<boolean> {
  try {
    await getFbAppId();
    await getFbAppSecret();
    return true;
  } catch {
    return false;
  }
}

function requireEnv(name: string): string {
  const val = process.env[name];
  if (!val) throw new Error(`Missing required env var: ${name}`);
  return val;
}

/**
 * Scopes required for Marketing OS page integration.
 *
 * `read_insights` removed (Meta 2024+): it is Advanced Access only and not
 * shown in Graph Explorer's standard picker. `pages_read_engagement` covers
 * page_fans / page_impressions / post-level metrics for page admins, which is
 * the only persona we support.
 *
 * `ads_read` (Phase 1 Marketing Ads): read-only ad account insights — spend,
 * impressions, clicks, CTR, CPM, ROAS. Required for /ads dashboard. Meta
 * approval ~1-3 tuần qua App Review (cần submit screencast + use case).
 * Sau khi user reconnect FB, app cùng lúc lấy:
 *   - access token cho Pages (đã có)
 *   - access token cho Ad accounts (qua /me/adaccounts với cùng user token)
 * Cùng 1 OAuth flow, không phải reconnect 2 lần.
 */
const OAUTH_SCOPES = [
  'pages_show_list',
  'pages_read_engagement',
  'ads_read',
].join(',');

/**
 * Build the Facebook OAuth dialog URL.
 * `state` is a CSRF token generated by the connect route and verified in callback.
 * Async giờ vì credentials có thể nằm trong DB (encrypted) thay vì env.
 */
export async function buildAuthUrl(state: string): Promise<string> {
  const appId = await getFbAppId();
  const redirectUri = requireEnv('FB_REDIRECT_URI');

  const params = new URLSearchParams({
    client_id: appId,
    redirect_uri: redirectUri,
    scope: OAUTH_SCOPES,
    state,
    response_type: 'code',
  });

  return `${FB_BASE}/${FB_VERSION}/dialog/oauth?${params.toString()}`;
}

/** Exchange authorization code for a short-lived user access token. */
export async function exchangeCodeForUserToken(code: string): Promise<string> {
  const appId = await getFbAppId();
  const appSecret = await getFbAppSecret();
  const redirectUri = requireEnv('FB_REDIRECT_URI');

  const params = new URLSearchParams({
    client_id: appId,
    client_secret: appSecret,
    redirect_uri: redirectUri,
    code,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/oauth/access_token?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB token exchange failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { access_token?: string; error?: { message: string } };
  if (data.error || !data.access_token) {
    throw new Error(`FB token exchange error: ${data.error?.message ?? 'no access_token'}`);
  }

  return data.access_token;
}

/**
 * Exchange a short-lived user token (~1h) for a long-lived user token (~60 days).
 * FB documentation: https://developers.facebook.com/docs/facebook-login/guides/access-tokens/get-long-lived
 */
export async function extendUserToken(shortToken: string): Promise<string> {
  const appId = await getFbAppId();
  const appSecret = await getFbAppSecret();

  const params = new URLSearchParams({
    grant_type: 'fb_exchange_token',
    client_id: appId,
    client_secret: appSecret,
    fb_exchange_token: shortToken,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/oauth/access_token?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB token extension failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { access_token?: string; error?: { message: string } };
  if (data.error || !data.access_token) {
    throw new Error(`FB token extension error: ${data.error?.message ?? 'no access_token'}`);
  }

  return data.access_token;
}

/**
 * List all pages the user administers.
 * Returns page id, name, page-scoped access_token, and category.
 */
export async function listUserPages(userToken: string): Promise<FBPage[]> {
  const params = new URLSearchParams({
    fields: 'id,name,access_token,category',
    access_token: userToken,
  });

  const res = await fetch(
    `${GRAPH_BASE}/${FB_VERSION}/me/accounts?${params.toString()}`,
    { method: 'GET' }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`FB list pages failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as FBPaginatedResponse<FBPage> & {
    error?: { message: string };
  };

  if ('error' in data && data.error) {
    throw new Error(`FB list pages error: ${data.error.message}`);
  }

  return data.data ?? [];
}
