version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: marketing
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: marketing_os
    ports:
      - '5434:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev:
