import type { Metadata } from "next";
import { Montserrat, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

// Montserrat — display font cho toàn app. Subset 'vietnamese' để hiển thị đúng dấu tiếng Việt.
const montserrat = Montserrat({
  variable: "--font-sans-app",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* Sonner Toaster — mount tại root để toast.success/info/warning/error
            được hiển thị từ bất kỳ trang nào (login, dashboard, channels...).
            position=top-right để không bị navbar/footer che. richColors=true
            cho màu nền theo từng level (xanh/đỏ/vàng). */}
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
